version: '3.4'

services:
  flask:
    build:
      context: ./flask
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./flask:/usr/src/app
    ports:
      - 5000:5000

  mongo:
    image: 'mongo:4.2.6-bionic'
    env_file:
      - .env
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo/db:/data/db
      - ./mongo/init-scripts:/docker-entrypoint-initdb.d